### ISSUE TITLE
code source of loki_0.3.0-r502-1_amd64.deb

### ISSUE THREAD

**Issue by Raizo62** [Raizo62/Loki_on_Kali#4]
Hi @0xc0decafe

Can we have access to the source code of loki_0.3.0-r502-1 ? (i think to C code of asleap, bf, mplsred, ...)

Thanks

**Comment by 0xc0decafe** [comment]
Hi,

the code is public since the first release. find it here: https://c0decafe.de/svn/codename_loki/

best

**Comment by Raizo62** [comment]
Hi

Yes, i know this url, but the last version showed is 0.2.7

Or, the 0.3.0 is the subfolder "trunk" ?

**Comment by 0xc0decafe** [comment]
yes, you'll find revision 502 in trunk.

**Comment by Raizo62** [comment]
Thanks :-)
