### ISSUE TITLE
ImportError: cannot import name bf

### ISSUE THREAD

**Issue by jargonx86** [Raizo62/Loki_on_Kali#6]
First of all I would like to thank you for the great work. Unfortunately the cracking of data does not work for me. The following message appears: 

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/share/loki/modules/module_ospf.py", line 1093, in run
    from loki_bindings import bf
ImportError: cannot import name bf

Thanks for your help.

**Comment by Raizo62** [comment]
Hi

With which Linux distribution did you have this problem ? (Kali / Parrot OS / ... ?)

Have you install the dependencies with the local or apt packages ?

**Comment by jargonx86** [comment]
Hello, thanks for helping me.
I am using Kali Linux (2022.1) and I tried both ways (with local and apt packaages) but get the same problem.  Also, I tried the same with a fresh ParrotOS installation. But it also did not work. Under which version (kali or parrotOS) did you test it?

**Comment by Raizo62** [comment]
I tested now with a fresh "kali-linux-2022.2-virtualbox-amd64.ova"
I installed the necessary packages with the apt method
I ran "loki_gtk.py"
I have no errors.

Are you sur that you have no error when installing the necessary packages ?

**Comment by jargonx86** [comment]
Strange, I have now tried different kali and parrotOS linux versions and always get the same error. The same happens with my colleagues who have also tested the software. Basically the software works fine, but as soon as a PCAP file is uploaded (e.g. BGP communication) and an attempt is made to crack the key, the error appears (-> StackTrace). The error only occurs whether you try to crack the OSPF, BGP, HSRP communication (based on the imported pcap file).

**Comment by Raizo62** [comment]
I believe the program is trying to load the library  "bf" but it can't find it (or it doesn't want to).
But this file is here `/usr/lib/pyshared/python2.7/loki_bindings/bf.so`

**Comment by Raizo62** [comment]
Could you try this temporary solution : 
```
touch /usr/lib/pyshared/python2.7/loki_bindings/__init__.py
sudo env PYTHONPATH=/usr/lib/pyshared/python2.7/ loki_gtk.py
```

**Comment by jargonx86** [comment]
Thanks a lot. This solution works fine! Have a great day

**Comment by Raizo62** [comment]
Could you test also this better solution ? : 
```
mv /usr/lib/pyshared/python2.7/loki_bindings/*.so /usr/local/lib/python2.7/dist-packages/loki_bindings/
rm /usr/lib/pyshared/python2.7/loki_bindings/ -r

sudo loki_gtk.py
```

**Comment by jargonx86** [comment]
This solution works perfectly for me. Thank you very much for your help and for providing your code!

**Comment by Raizo62** [comment]
Thank you for this ticket and your help :-)
